<?php

/**
 * Placeholder implementation of hook_menu
 *
 * TODO Use or remove this hook
 */
function hosting_matrix_menu() {
  $items = array();
  $items['admin/hosting/matrix'] = array(
    'title' => 'Server Matrix settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_matrix_settings'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['hosting/matrix_clients'] = array(
    'title' => 'Server matrix',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_matrix_clients_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['hosting_matrix/task/%/%'] = array(
    'page callback' => 'hosting_matrix_view_task',
    'page arguments' => array(2, 3),
    // TODO: Permission
    'access arguments' => array('access task logs'),
  );

  return $items;
}

function hosting_matrix_view_task($server_nid, $task_nid) {
  $node = hosting_matrix_get_task($server_nid, $task_nid);

  if ($node) {
    $log = hosting_matrix_get_task_log($server_nid, $task_nid);

    $html = _hosting_matrix_task_log_table($log);
    return drupal_render($html);
  }
}

function hosting_matrix_get_task($server_nid, $task_nid) {
  // TODO
  $base_url = 'http://hosting_matrix.local/hosting_matrix_client';

  $data = array();
  $base_url = '';
  $response = hosting_matrix_connect($server_nid, $data, $base_url);

  $platforms = array();

  if ($response->code == 200) {
    $options['headers']['Cookie'] = $data->session_name . '=' . $data->sessid;
    $options['method'] = 'GET';

    $response = drupal_http_request($base_url . '/hosting_task/' . $task_nid, $options);
    return json_decode($response->data);
  }
}

function hosting_matrix_get_task_log($server_nid, $task_nid) {
  // TODO
  $base_url = 'http://hosting_matrix.local/hosting_matrix_client';

  $data = array();
  $base_url = '';
  $response = hosting_matrix_connect($server_nid, $data, $base_url);

  $platforms = array();

  if ($response->code == 200) {
    // Use the cookie and the Token for the POST request
    $options['headers']['Cookie'] = $data->session_name . '=' . $data->sessid;
    $options['headers']['X-CSRF-Token'] = $data->token;

    $options['data'] = http_build_query(array('nid' => $task_nid,), '', '&');
    $options['method'] = 'POST';
    $response = drupal_http_request($base_url . '/hosting_task/get_task_log', $options);
    $messages = json_decode($response->data);

    return $messages;
  }
}

function hosting_matrix_clients_form($form, &$form_state) {
  $matrix_clients = hosting_get_servers('matrix_client');

  foreach($matrix_clients as $nid => $hostname) {
    $node = node_load($nid);

    $prefix = '<fieldset class="collapsible" id="hosting-matrix-server-"' . $nid . '">';
    $prefix .= '<strong>Server: ' . $hostname . '</strong>';

    $form['hosting_matrix_' . $nid] = array(
      '#type' => 'markup',
      '#title' => t('Server'),
      '#markup' => _hosting_matrix_get_server_markup($nid),
      '#prefix' => $prefix,
      '#suffix' => '</fieldset>',
    );
  }

  return $form;
}

function _hosting_matrix_get_server_markup($nid) {
  // TODO: This is the local nid! Remove this. Make a list of servers?
  $tasks = hosting_matrix_get_task_list($nid);
  $platforms = hosting_matrix_get_platform_list($nid);

  $html = '';
  $html .= '<div>';
  $html .= hosting_matrix_task_table($tasks, $nid);
  $html .= '</div>';
  $html .= '<div>';
  $html .= theme('hosting_matrix_platform_list', array('platforms' => $platforms));
  $html .= '</div>';

  return $html;
}

function hosting_matrix_theme($existing, $type, $theme, $path) {
  return array(
    'hosting_matrix_platform_list' => array(
      'variables' => array('platforms' => NULL),
    ),
  );
}

function theme_hosting_matrix_platform_list($variables) {
  $platforms = $variables['platforms'];

  $header = array(
    t('Platform'),
    t('Release'),
    t('Server'),
    t('Verified'),
    t('Sites'),
  );

  $rows[] = array();

  $total = 0;
  foreach ($platforms as $node) {
    $row = array();
    $row[] = array(
      'class' => array('hosting-status'),
      // TODO
      'data' => '<a href="/todo">' . $node->title . '</a>',
    );
    $release = sprintf("%s %s", $node->release->title, $node->release->version);
    $row[] = $release;
    $row[] = $node->web_server;
    $row[] = hosting_format_interval($node->verified);
    //TODO
    $total += 1;
    $row[] = count($node->sites);
    $rows[] = array(
      'data' => $row,
      'class' => array(_hosting_platform_list_class($node->platform_status)),
    );
  }
  $row = array();
  $row[] = array(
    'data' => t('Total sites hosted'),
    'colspan' => 4,
  );
  $row[] = $total;
  $rows[] = $row;

  return theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('class' => array('hosting-table'))));
}

function hosting_matrix_get_platform_list($server_nid) {
  // TODO
  $base_url = 'http://hosting_matrix.local/hosting_matrix_client';
  
  $data = array();
  $base_url = '';
  $response = hosting_matrix_connect($server_nid, $data, $base_url);

  $platforms = array();

  if ($response->code == 200) {
    // Use the cookie and the Token for the POST request
    $options['headers']['Cookie'] = $data->session_name . '=' . $data->sessid;
    $options['headers']['X-CSRF-Token'] = $data->token;
  
    $data = array();
    $options['data'] = http_build_query($data, '', '&');
    $options['method'] = 'GET';

    $response = drupal_http_request($base_url . '/hosting_platform', $options);
    $data = json_decode($response->data);

    foreach ($data as $platform) {
      $options['data'] = http_build_query($data, '', '&');
      $options['method'] = 'GET';
      $response = drupal_http_request($base_url . '/hosting_platform/' . $platform->nid, $options);
      $platform_data = json_decode($response->data);

      $platforms[$platform_data->nid] = $platform_data;

      $options['data'] = http_build_query(array('nid' => $platform->nid,), '', '&');
      $options['method'] = 'POST';
      $response = drupal_http_request($base_url . '/hosting_platform/sites', $options);
      $sites = json_decode($response->data);

      $platforms[$platform_data->nid]->sites = (array)$sites;
    }
  }
  else {
    drupal_set_message(t('An error occured while trying to connect to !hostname. Check the configuration.', array('!hostname' => $host)), 'error');
  }

  return $platforms;
}

function hosting_matrix_get_task_list($nid) {
  $data = array();
  $base_url = '';
  $response = hosting_matrix_connect($nid, $data, $base_url);

  $platforms = array();

  if ($response->code == 200) {
    // Use the cookie and the Token for the POST request
    $options['headers']['Cookie'] = $data->session_name . '=' . $data->sessid;
    $options['headers']['X-CSRF-Token'] = $data->token;

    $options['data'] = http_build_query(array('nid' => $nid,), '', '&');
    $options['method'] = 'POST';
    $response = drupal_http_request($base_url . '/hosting_task/get_task_list', $options);
    $tasks = json_decode($response->data);

    return (array) $tasks;
  }  
}

function hosting_matrix_connect($server_nid, &$data, &$base_url) {
  $node = node_load($server_nid);

  if ($node) {
    // TODO: https
    $base_url = 'http://' . $node->title . '/hosting_matrix_client';
  }
  else {
    return;
  }

  // TODO
  $data = array(
    'username' => 'admin',
    'password' => 'test',
  );

  $data = drupal_json_encode($data);

  $options = array(
    'headers' => array(
      'Content-Type' => 'application/json',
    ),
    'method' => 'POST',
    'data' => $data
  );

  $response = drupal_http_request($base_url . '/user/login', $options);
  $data = json_decode($response->data);

  return $response;
}


function hosting_matrix_settings($form, &$form_state) {
  return system_settings_form($form);
}

/**
 * TODO: Implement hook_permission().
 */

/**
 * Implements hook_hosting_service_type().
 */
function hosting_matrix_hosting_service_type() {
  return array(
    'matrix_client' => array(// Machine name
      'title' => t('Matrix client'), // Human-readable name
      'weight' => 0, // Optional, defaults to 0
    ),
  );
}

/**
 * Implements hook_hosting_service().
 */
function hosting_matrix_hosting_service() {
  return array('hostmaster' => 'matrix_client'); // Service implementation => service type.
}

function hosting_matrix_task_table($tasklist, $server_nid) {
  $output = '';

  $headers[] = t('Task');
  $headers[] = array(
    'data' => t('Actions'),
    'class' => array('hosting-actions'),
  );

  $rows = array();

  foreach ($tasklist as $task => $info) {
    $row = array();

    $info = (array) $info;

    if (!isset($info['nid']) && !$info['task_permitted']) {
      // just don't show those tasks, since we'll not be able to run them
      continue;
    }

    $row['type'] = array(
      'data' => $info['title'],
      'class' => array('hosting-status'),
    );
    $actions = array();


    // TODO: The buttons, they do nothing.

    if (isset($info['task_status']) && ($info['task_status'] == 0)) {
//      $actions['cancel'] = _hosting_task_button(t('Cancel'), sprintf("hosting/tasks/%d/cancel", $info['nid']), t("Cancel the task and remove it from the queue"), 'hosting-button-stop', !$info['task_permitted']);
//      $actions['cancel'] = _hosting_task_button(t('Cancel'), sprintf("hosting/tasks/%d/cancel", $info['nid']), t("Cancel the task and remove it from the queue"), 'hosting-button-stop', !$info['task_permitted']);
    }
    else {
//      $actions['run'] = _hosting_task_button(t('Run'), sprintf("hosting_confirm/%d/%s_%s", 'TODO', 'TODO', $task), $info['description'], 'hosting-button-run', $info['task_permitted'], $info['dialog']);
      $actions['run'] = _hosting_task_button(t('Run'), sprintf("hosting_confirm/%d/%s_%s", 'TODO', 'TODO', $task), $info['description'], 'hosting-button-run', FALSE, $info['dialog']);
    }

    $actions['log'] = _hosting_task_button(t('View'), isset($info['nid']) ? 'hosting_matrix/task/' . $server_nid . '/' . $info['nid'] : '<front>', t("Display the task log"), 'hosting-button-log', isset($info['nid']), TRUE, FALSE);
    $row['actions'] = array(
      'data' => implode('', $actions),
      'class' => array('hosting-actions'),
    );

    $rows[] = array(
      'data' => $row,
      'class' => array($info['class']),
    );
  }
  $output .= theme('table', array('header' => $headers, 'rows' => $rows, 'attributes' => array('class' => array('hosting-table'))));
  return $output;
}

/**
 * Display table containing the logged information for this task
 */
function _hosting_matrix_task_log_table($log) {
  if (!empty($log)) {
    $headers = array('data' => 'Log message', 'execution_time' => 'Execution time');
    $rows = array();
    $last_timestamp = 0;
    $exec_time = '';
    $row_count = -1;
    foreach ($log as $entry) {
      if (strlen($entry->message) > 300) {
        $summary = "<span class='hosting-task-summary'>" . filter_xss(substr($entry->message, 0, 75), array()) . "... <a href='javascript:void(0)' class='hosting-summary-expand modalframe-exclude'>(" . t('Expand') . ')</a></span>';
        $message = $summary . "<span class='hosting-task-full'>" . filter_xss($entry->message) . '</span>';
      }
      else {
        $message = filter_xss($entry->message);
      }

      // Add error and warning anchors, so we can provide a quick link to them.
      if ($entry->type == 'error') {
        $message = '<a name="error"></a>' . $message;
      }
      elseif ($entry->type == 'warning') {
        $message = '<a name="warning"></a>' . $message;
      }

      // Add the exec_time to the previous row
      $exec_time = $entry->timestamp - $last_timestamp;

      // "1" is unreliable because timestamps don't allow sub-second granularity
      if ($exec_time < 1) {
        $exec_time = '<div>-</div>';
      }
      else if ($exec_time == 1) {
        $exec_time = '<div title="Many tasks take less than 1 second to perform. This duration represents an aggregate of the preceding tasks\' duration."><strong>' . $exec_time . ' s.</strong></div>';
      }
      else {
        $exec_time = '<div><strong>' . $exec_time . ' s.</strong></div>';
      }

      if ($row_count > -1) {
        $rows[$row_count]['data'][] = array(
          'data' => $exec_time,
        );
      }

      $row_count++;
      $last_timestamp = $entry->timestamp;

      $row = array(
        array(
          'data' => $message,
          'class' => array('hosting-status'),
        ),
      );

      $rows[] = array(
        'data' => $row,
        'class' => array(_hosting_task_log_class($entry->type)),
      );

      // Record that we've seen this log row.
      $last_lid = $entry->lid;
    }

    return array(
      '#theme' => "table",
      '#header' => $headers,
      '#rows' => $rows,
      '#attributes' => array(
        'id' => 'hosting-task-log',
        'class' => array(
          'hosting-table',
        ),
      ),
    );
  }

  return FALSE;
}
